### ISSUE TITLE
Need Your Kind Guidance

### ISSUE THREAD

**Issue by SyedKumailHussainNaqvi** [lbwfff/my-learning#1]
Hi @lbwfff ,
I came across your question on the CAMP GitHub page regarding so I am seeking your assistance in this matter. I hope that you are able to provide the help I need in this regard.
I am currently experiencing a challenge with the target-mapping stage. Specifically, after generating an alignment_result file using the An SIMD Smith-Waterman C/C++ method, I encountered an error when attempting to pass this file to the target-mapping step.

108 target[name]=seq
109 return target
--> 110 peptide_resolution_dict=get_result_dict()
111 pdb_uniprot_map=get_pdb_to_uniprot_map(peptide_resolution_dict)
112 query_residues=get_query_residue()

Input In [47], in get_result_dict()
16 seq_target, seq_query, align = '', '', ''
17 else:
---> 18 seq_target += line.split('\t')[1]
19 #print('seq_target',seq_target)
20 elif i%4 == 1:

IndexError: list index out of range

Kindly Help and guide me in this regards.
[alignment_result.txt](https://github.com/lbwfff/my-learning/files/11935452/alignment_result.txt)

**Comment by lbwfff** [comment]
I tried using CAMP over a year ago, but have unfortunately not reproduced the results, sorry for not being able to offer valid advice.
